# Generated by Django 3.2.4 on 2021-06-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210625_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
