# Generated by Django 3.2.3 on 2021-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist_id',
            field=models.IntegerField(),
        ),
    ]
